require 'spec_helper'
require 'spec/mocks'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by the Rails when you ran the scaffold generator.

describe UserDaysController do

  before :each do
    subject.stub :authenticate_user!
  end

  def mock_user_day(stubs={})
    @mock_user_day ||= mock_model(UserDay, stubs).as_null_object
  end

  describe "GET index" do
    it "assigns all user_days as @user_days" do
      pending "no it doesn't"
      UserDay.stub(:all) { [mock_user_day] }
      get :index
      assigns(:user_days).should eq([mock_user_day])
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "assigns a newly created user_day as @user_day" do
        UserDay.stub(:new).with({'these' => 'params'}) { mock_user_day(:save => true) }
        post :create, :user_day => {'these' => 'params'}
        assigns(:user_day).should be(mock_user_day)
      end

      it "redirects to the user days root" do
        UserDay.stub(:new) { mock_user_day(:save => true) }
        post :create, :user_day => {}
        response.should redirect_to(user_days_url)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved user_day as @user_day" do
        UserDay.stub(:new).with({'these' => 'params'}) { mock_user_day(:save => false) }
        post :create, :user_day => {'these' => 'params'}
        assigns(:user_day).should be(mock_user_day)
      end

      it "redirects to the user days root" do
        UserDay.stub(:new) { mock_user_day(:save => false) }
        post :create, :user_day => {}
        response.should redirect_to(user_days_url)
      end
    end
  end

end
